### ISSUE TITLE
Any plans for Bootstrap 4?

### ISSUE THREAD

**Issue by shyim** [conexco/shopware-bootstrap-theme#2]
Are they plans to upgrade to bs4?

**Comment by oktupol** [comment]
We are indeed planning to upgrade to Bootstrap 4, but there are some difficulties to be solved first. The biggest one is how we are going to integrate Bootstrap 4's Sass styles into Shopware's Less-compiler. Ideally, we don't want to lose the ability to configure variables for whichever preprocessor through the Theme Manager, and we haven't found a solution to do that yet.

**Comment by shyim** [comment]
Hmm thats annoying. I guess the easiest solution were a php sass compiler like less.php which is included in shopware (https://packagist.org/packages/leafo/scssphp).
It has the same abilities like the less.php compiler. Plugins less files could be compiled normal with less.php and included in the compiled css file

Process like:
* Collect all plugin less files and compile it to a specfic file
* Start the sass php compiler and include the output from less
* Save it normaly in /web/cache folder like the current process

It's a "dirty" solution or we get shopware to switch to sass 😂

**Comment by oktupol** [comment]
I was thinking about doing something similar. I'll try that :slightly_smiling_face:

**Comment by Miw0** [comment]
I don't think adding another php compiler for sass files will be a good idea. The current less-php compiler is slow, has bugs and lacks some features of Less so adding another compiler should be avoided.

So the only feasible solution would be Shopware upgrading from Less to Sass but I guess this will take a very long time (maybe with the release of Shopware 6).

**Comment by Blur-Creative** [comment]
i saw in the shopware dev branch they still using less :/

**Comment by alabama** [comment]
Adding another php based compiler for sass is indeed not a good solution but hoping that shopware will switch to SASS isn't either... 
How about adding some kind of a port? There are some dev-tools to port sass to less, even a bootstrap-4 less port:
https://github.com/mediafreakch/less-plugin-sass2less (unfortunately one open issue for helping to port bootstrap 4 ...)
https://github.com/seanCodes/bootstrap-less-port

So what's the status of the bootstrap 4 integration?

**Comment by raablx** [comment]
Hey guys,
what's the status of the bootstrap 4 integration?

**Comment by uehler** [comment]
we started testing with bootstrap 4 a while ago on a separate branch https://github.com/conexco/shopware-bootstrap-theme/tree/bootstrap-4-wip

**Comment by csaeum** [comment]
I am currently testing and building a theme based on bootstrap.

How safe would a switch to 4-WIP already be?

At the moment there is not much going on here, what about 5.5 or 5.5.x.

**Comment by benjamin-ott** [comment]
It's not safe to switch to bs4-WIP, because it's more of a concept branch. 
We still haven't solved the less/sass issue. 

In my opinion it's not a good idea to use a bootstrap 4 less port like https://github.com/seanCodes/bootstrap-less-port, because you would always be dependent on others to update the port (if a new bootstrap bugfix version is published).

At the moment we are looking into the possibility of compiling bootstrap ourselves (with the custom colors, modules, etc.) and importing it in the themes all.less. 
Something like this could be used to speed up the process: https://hackerthemes.com/kit/

But there are major downsides as well because wo wouldn't be able to use variables and mixins from bootstrap anymore.

**Comment by csaeum** [comment]
Okay then I know that.

@ benjamin-ott how can I ask 1-2 questions to you. Because I just have a problem with the https://www.bootstrap.de/docs/customisation.html and also the code at GitHub does not work with 5.5.x.

**Comment by ppowalowski** [comment]
Can anyone explain where the issue is? 
Of course template configuration from the backend would be dropped by moving forward to a modern front-end approach. Having a focus on developing a good state-of-the-art sass theme should avoid things like this anyways.
A PHP parser for sass would clearly be a bad choice as can be seen from the frightening results with the current less integration. Basically all shopware-shops out there build upon the messy predelivered theme usually with >600kb of css, because nobody really dares to mess with the built in front-end constraints given by the responsive theme (..and its less aproach).

I can clearly see and understand the argument for the possibility to compile styles from a php-driven user interface. But due to the downsides of introducing a preassumption I honestly wonder why there is just so little backlash from sane front-end devs to evolve away from the issues this causes around the responsive theme. A universal solution would be for Shopware to integrate a variable replacement in css instead of having to parse less. (similar to **shipify's .css.liquid** files).

**Solution:** Offer a CLI script to recompile styles should be effective enough for professionals. If somebody really needs to compile themes in production, a cli bridge from php can be somehow built. No front-end developer would voluntarily use things like this super slow less php parser. 
As of seperation of concerns there should be freedom about the front-end and this less preassumption integrated into Shopware is clearly a disadvantage making the theme no fun to work with.

I would like to see more independent themes like it's totally usual for any other platform out there. You can find any technique and approach in available Magento or Shopify themes.  Shopware should get out of the way with this oldschool less approach and encourage the community development by dropping this less parser out, thus removing this dependency.  Maybe they could give some sort of settings framework to make any theme configurable. As far as I am concerned we managed to implement a store quite nicely In Shopify by compiling sass locally into the css.liquid files which were then fed by Shopify confguration parameters.

**Conclusion:** There is no "less/sass" issue. I think it needs to be called out that this less approach in Shopware is a mess and instead of trying to comply to this and "finding a solution for the less/sass problem" Shopware could better drop this whole approach and offer a more convenient and universal way of integrating theme configuration. Otherwise theme development for Shopware will more and more feel like a historical time-travel.

**Comment by thomasfrobieter** [comment]
I 100% agree with @ppowalowski, Shopware kills my worflow with this nonsenseless Less online compiler. Furthermore i prefer SASS over LESS .. but for sure, this is just my personal preference.

I have also some experience with the PHP port of the SASS compiler and i can't recommend using this.

**Comment by shyim** [comment]
Its not required anymore due https://github.com/shopware/platform
